Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2024
Var
   // Seção de Declarações das variáveis
   AC1, AC2, PEX, AVR, Media, media_final : real
   Nome : Caracter
   resultado :  Logico

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo